/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackToTop: typeof import('./components/BackToTop/index.vue')['default']
    CommentItem: typeof import('./components/CommentItem/index.vue')['default']
    EditUserInfo: typeof import('./components/EditUserInfo/index.vue')['default']
    ErrorPage: typeof import('./components/ErrorPage/index.vue')['default']
    QuestionCard: typeof import('./components/QuestionCard/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubTab: typeof import('./components/SubTab/index.vue')['default']
    TestBasket: typeof import('./components/TestBasket/index.vue')['default']
    TestCard: typeof import('./components/TestCard/index.vue')['default']
    UploadQuestion: typeof import('./components/UploadQuestion/index.vue')['default']
    VirtualList: typeof import('./components/VirtualList/index.vue')['default']
  }
}

// For TSX support
declare global {
  const BackToTop: typeof import('./components/BackToTop/index.vue')['default']
  const CommentItem: typeof import('./components/CommentItem/index.vue')['default']
  const EditUserInfo: typeof import('./components/EditUserInfo/index.vue')['default']
  const ErrorPage: typeof import('./components/ErrorPage/index.vue')['default']
  const QuestionCard: typeof import('./components/QuestionCard/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SubTab: typeof import('./components/SubTab/index.vue')['default']
  const TestBasket: typeof import('./components/TestBasket/index.vue')['default']
  const TestCard: typeof import('./components/TestCard/index.vue')['default']
  const UploadQuestion: typeof import('./components/UploadQuestion/index.vue')['default']
  const VirtualList: typeof import('./components/VirtualList/index.vue')['default']
}